name: CI/CD Tienda Perritos - Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  # --- NUEVO JOB PARA DOCKER HUB ---
  build-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build docker
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ayanezz92/tienda-frontend:latest

  # --- JOB ORIGINAL PARA AWS ---
  build-push-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-push-dockerhub
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO: ${{ secrets.ECR_REPO_URL_FRONTEND }}
        run: |
          docker build -t tienda-frontend ./frontend
          docker tag tienda-frontend $ECR_REGISTRY/$ECR_REPO:latest
          docker push $ECR_REGISTRY/$ECR_REPO:latest

      - name: Despliegue en EC2 vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
              "docker stop tienda-frontend || true",
              "docker rm tienda-frontend || true",
              "docker run -d --name tienda-frontend -p 80:80 ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_FRONTEND }}:latest"
            ]'