name: CI/CD Tienda Perritos - DB

on:
  push:
    paths:
      - 'db/**'
  workflow_dispatch: # Permite ejecución manual desde la pestaña Actions

jobs:
  # HITO 1: Subida a Docker Hub (Según imagen image_bf2111.jpg)
  build-push-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: login dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build docker
        uses: docker/build-push-action@v5
        with:
          context: ./db
          push: true
          tags: ayanezz92/tienda-db:latest

  # HITO 2 y 4: AWS ECR y Despliegue en EC2
  build-push-deploy-db:
    runs-on: ubuntu-latest
    needs: build-push-dockerhub # Espera a que termine el job de Docker Hub
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build y Push ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPO: ${{ secrets.ECR_REPO_URL_DB }}
        run: |
          docker build -t tienda-db ./db
          docker tag tienda-db $ECR_REGISTRY/$ECR_REPO:latest
          docker push $ECR_REGISTRY/$ECR_REPO:latest

      - name: Despliegue en EC2 vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_DB_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_DB }}:latest",
              "docker stop tienda-db || true",
              "docker rm tienda-db || true",
              "docker run -d --name tienda-db -p 3306:3306 -v db_data:/var/lib/mysql ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPO_URL_DB }}:latest"
            ]'